### ISSUE TITLE
When specifying [] for ice servers in export mode, get TypeError: Value is not a sequence adapter.js:2135

### ISSUE THREAD

**Issue by rajha-korithrien** [cloudonix/sipml5-ng#2]
If you use the "expert mode" UI and place "[]" for ICE Servers in order to disable the use of ICE for constructing candidate entries. You get the above mentioned error.

The issue is made manifest due to line 2119 of adapter.js, this if condition:
```
if (pcConfig && pcConfig.iceServers) {
...
}
return new OrigPeerConnection(pcConfig, pcConstraints);
```
pcConfig.iceServers is null and thus the if block is never entered. The code inside the if block would, if executed, construct pcConfig.iceServers and thus avoid the error.

It is not immediately obvious to me why pcConfig.iceServers is null instead of an empty array. Figuring this out would show the "root" of the problem and would be the better place to solve it.

A workaround is to add an edge case to the if statement:
```
if (pcConfig && pcConfig.iceServers) {
...
} else if (pcConfig) {
    pcConfig.iceServers = [];
}
return new OrigPeerConnection(pcConfig, pcConstraints);
```
In this code if pcConfig.iceServers is null, but pcConfig exists, then pcConfig.iceServers is an empty array and things work as expected.

**Comment by greenfieldtech-nirs** [comment]
Hi Rajha,

Can you please open a full pull-request on this - so that we can examine it properly.
